module.exports.ALGORITHM = 'sha256'
module.exports.API_HEADER = 'x-api-token'
module.exports.APPLICATION_JSON = 'application/json'
module.exports.AUTH_HEADER = 'authorization'
module.exports.CONTENT_LENGTH_HEADER = 'content-length'
module.exports.CONTENT_TYPE_HEADER = 'content-type'
module.exports.EXPIRE_TIME = '24h'
module.exports.SECRET = '🍌'
